services:
  - type: web
    name: voting-backend
    env: node
    plan: free
    buildCommand: cd voting && npm install
    startCommand: cd voting && npm start
    envVars:
      - key: NODE_ENV
        value: production
