services:
  - type: web
    name: voting-backend
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && npm install --prefix backend
    startCommand: bash start-all.sh
    envVars:
      - key: NODE_ENV
        value: production
